-- find total number of customers by countries
SELECT
country,
COUNT(customer_key) AS numberofcustomers
FROM gold.dim_customers
GROUP BY country
ORDER BY numberofcustomers DESC

--find total customer by gender
SELECT
gender,
COUNT(customer_key) totalcustomers
FROM gold.dim_customers
GROUP BY gender	
ORDER BY totalcustomers DESC

--find total products by category
SELECT
category,
COUNT(product_id) totalproducts
FROM gold.dim_products
GROUP BY category
ORDER BY totalproducts DESC

--what is the average costs in each category
SELECT
category,
AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--what is the total revenue generated for each country
SELECT
P.category,
SUM(s.sales_amount) AS total_sales
FROM gold.dim_products p
INNER JOIN gold.fact_sales s
	ON p.product_key=s.product_key
GROUP BY p.category
ORDER BY total_sales DESC

-- total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) AS total_revenue
FROM gold.fact_sales s 
LEFT JOIN gold.dim_customers c 
	ON s.customer_key=c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- what is the distrubution of sold items across countries
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
	ON f.customer_key=c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
